In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
del_cost=1
ins_cost=1
sub_cost=2

In [11]:
def calculate_minimum_edit_distance(source, target):
    n = len(source)
    m = len(target)
    MED_matrix = np.zeros((n+1, m+1), dtype='int32')
    for i in range(1, n+1):
        MED_matrix[i][0] = MED_matrix[i-1][0]+ del_cost
    for i in range(1, m+1):
        MED_matrix[0][i] = MED_matrix[0][i-1]+ del_cost
    
    for i in range(1, n+1):
        for j in range(1, m+1):
            if(source[i-1] == target[j-1]):
                MED_matrix[i][j] = min([MED_matrix[i-1][j]+del_cost, 
                                       MED_matrix[i-1][j-1]+0, MED_matrix[i][j-1]+ins_cost])
                
            else : 
                MED_matrix[i][j]=min([MED_matrix[i-1][j]+del_cost,MED_matrix[i-1][j-1]+sub_cost,MED_matrix[i][j-1]+ins_cost])

    print(MED_matrix)
    return MED_matrix[n][m]


In [12]:
calculate_minimum_edit_distance('This is a cat','This is a dog')

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  0  1  2  3  4  5  6  7  8  9 10 11 12]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11]
 [ 3  2  1  0  1  2  3  4  5  6  7  8  9 10]
 [ 4  3  2  1  0  1  2  3  4  5  6  7  8  9]
 [ 5  4  3  2  1  0  1  2  3  4  5  6  7  8]
 [ 6  5  4  3  2  1  0  1  2  3  4  5  6  7]
 [ 7  6  5  4  3  2  1  0  1  2  3  4  5  6]
 [ 8  7  6  5  4  3  2  1  0  1  2  3  4  5]
 [ 9  8  7  6  5  4  3  2  1  0  1  2  3  4]
 [10  9  8  7  6  5  4  3  2  1  0  1  2  3]
 [11 10  9  8  7  6  5  4  3  2  1  2  3  4]
 [12 11 10  9  8  7  6  5  4  3  2  3  4  5]
 [13 12 11 10  9  8  7  6  5  4  3  4  5  6]]


6

In [13]:
calculate_minimum_edit_distance('Aadesh', 'aadesss')

[[0 1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7 8]
 [2 1 2 3 4 5 6 7]
 [3 2 3 2 3 4 5 6]
 [4 3 4 3 2 3 4 5]
 [5 4 5 4 3 2 3 4]
 [6 5 6 5 4 3 4 5]]


5